#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "custom_functions.h"

struct _dictionary_item cf_dictionary[] = {
        {"normalize_date_fortigate", normalize_date_fortigate, "(?P<year>\\d{4})-(?P<month>\\d+)-(?P<day>\\d+)\\s+time=(?P<hour>\\d+):(?P<minute>\\d+):(?P<second>\\d+)"},
        {"fortigate_sid",fortigate_sid,""},
        {"normalize_protocol", normalize_protocol, ""},
        {"normalize_date_citrix",normalize_date_citrix,"(?P<month>(0?[1-9])|(1[0-2]))/(?P<day>(1[0-9])|(2[0-9])|(3[0-1])|(0?[0-9]))/(?P<year>\\d{4}):(?P<hour>\\d{1,2}):(?P<minute>\\d{1,2}):(?P<second>\\d{1,2})"},
        {"translate_citrix",translate_citrix,""},
        {"", NULL}
};

struct citrix_dictionary c_dict[] = {
    {"UI CMD_EXECUTED","101"},
    {"GUI CMD_EXECUTED","102"},
    {"SNMP TRAP_SENT","201"},
    {"SNMP TRAP_DROPPED","202"},
    {"TCP CONN_DELINK","203"},
    {"TCP CONN_TERMINATE","204"},
    {"TCP OTHERCONN_DELINK","205"},
    {"TCP NAT_CONN_DELINK","206"},
    {"TCP NAT_OTHERCONN_DELINK","207"},
    {"ACL ACL_PKT_LOG","208"},
    {"AAA LOGIN_FAILED","209"},
    {"AAA EXTRACTED_GROUPS","210"},
    {"SSLVPN LOGIN","211"},
    {"SSLVPN LOGOUT","212"},
    {"SSLVPN ICASTART","213"},
    {"SSLVPN ICAEND_CONNSTAT","214"},
    {"SSLVPN TCPCONNSTAT","215"},
    {"SSLVPN TCPCONN_TIMEDOUT","216"},
    {"SSLVPN UDPFLOWSTAT","217"},
    {"SSLVPN HTTPREQUEST","218"},
    {"SSLVPN NONHTTP_RESOURCEACCESS_DENIED","219"},
    {"SSLVPN HTTP_RESOURCEACCESS_DENIED","220"},
    {"SSLVPN LICLMT_REACHED","221"},
    {"SSLVPN CLISEC_CHECK","222"},
    {"SSLVPN CLISEC_EXP_EVAL","223"},
    {"SSLVPN STA_VALIDATE_RESP","224"},
    {"SSLVPN REMOVE_SESSION","350"},
    {"SSLVPN Message","351"},
    {"SSLVPN REMOVE_SESSION_INFO","352"},
    {"SSLLOG SSL_HANDSHAKE_FAILURE","225"},
    {"SSLLOG SSL_HANDSHAKE_SUCCESS","226"},
    {"SSLLOG SSL_CERT_EXPIRY_IMMINENT","227"},
    {"SSLLOG SSL_HANDSHAKE_ISSUERNAME","228"},
    {"SSLLOG SSL_HANDSHAKE_SUBJECTNAME","229"},
    {"SSLLOG SSL_CRL_UPDATE_SUCCESS","230"},
    {"SSLLOG SSL_CRL_UPDATE_FAILURE","231"},
    {"ROUTING ZEBOS_CMD_EXECUTED","232"},
    {"ROUTING PAL","233"},
    {"ROUTING ROUTE_ADVERTISED","234"},
    {"ROUTING ROUTE_WITHDRAWN","235"},
    {"ROUTING ROUTE_RELEARN","236"},
    {"ROUTING ROUTE_HASTATE","237"},
    {"TRANSFORM FILE_REQUEST","238"},
    {"TRANSFORM REQ_PARSE_ERROR","239"},
    {"TRANSFORM REQ_HEADER","240"},
    {"TRANSFORM RESP_HEADER","241"},
    {"TRANSFORM BODY_FRAG","242"},
    {"TRANSFORM ACTION_MATCH","243"},
    {"TRANSFORM ACTION_MISMATCH","244"},
    {"TRANSFORM PCRE_ERROR","245"},
    {"TRANSFORM REQ_WRITE_ERROR","246"},
    {"AAATM LOGIN","247"},
    {"AAATM LOGOUT","248"},
    {"AAATM HTTPREQUEST","249"},
    {"AAATM HTTP_RESOURCEACCESS_DENIED","250"},
    {"AAATM Message","266"},
    {"ICA SESSION_SETUP","251"},
    {"ICA SESSION_UPDATE","252"},
    {"ICA SESSION_TERMINATE","253"},
    {"ICA NETWORK_UPDATE","254"},
    {"ICA APPLICATION_LAUNCH","255"},
    {"ICA APPLICATION_TERMINATE","256"},
    {"ICA Message","265"},
    {"PITBOSS PITBOSS","257"},
    {"PITBOSS PITBOSS","258"},
    {"PITBOSS PB_SYSTEM_RESTART","259"},
    {"PITBOSS PB_PROCESS_RESTART","260"},
    {"CVPN CVPN_INPUT_URL","261"},
    {"CVPN CVPN_REWRITTEN_URL","262"},
    {"CVPN CVPN_PCRE_ERROR","263"},
    {"CVPN CVPN_MATCHED_URL","264"},
    {"EVENT STARTSAVECONFIG","301"},
    {"EVENT STOPSAVECONFIG","302"},
    {"EVENT STATECHANGE","303"},
    {"EVENT DEVICEUP","304"},
    {"EVENT ROUTEUP","305"},
    {"EVENT ALERTSTARTED","306"},
    {"EVENT ALERTENDED","307"},
    {"EVENT STARTSYS","308"},
    {"EVENT STARTCPU","309"},
    {"EVENT DEVICEDOWN","310"},
    {"EVENT DEVICEOFS","311"},
    {"EVENT NICSTART","312"},
    {"EVENT NICSTOP","313"},
    {"EVENT NICHANG","314"},
    {"EVENT NICRESET","315"},
    {"EVENT NICMIGRATE","316"},
    {"EVENT STOPSYS","317"},
    {"EVENT FREEBADMEM","318"},
    {"EVENT FREEDUPMEM","319"},
    {"EVENT FREEEXTMEM","320"},
    {"EVENT PROPSUCCESS","321"},
    {"EVENT PROPFAIL","322"},
    {"EVENT CLSTATECHANGE","323"},
    {"EVENT CACHESTARTFLUSH","324"},
    {"EVENT CACHESTOPFLUSH","325"},
    {"EVENT MONITORTH","326"},
    {"EVENT MONITORDOWN","327"},
    {"EVENT MONITORUP","328"},
    {"EVENT ROUTEDOWN","329"},
    {"EVENT VRID6DOWN","330"},
    {"EVENT VRIDDOWN","331"},
    {"EVENT VRIDUP","332"},
    {"EVENT VRIDINIT","333"},
    {"EVENT VIPRHIUP","334"},
    {"EVENT VIPRHIDOWN","335"},
    {"EVENT CONFIGSTART","336"},
    {"EVENT CONFIGEND","337"},
    {"EVENT NICLACPSC","338"},
    {"EVENT NICPOWERON","339"},
    {"EVENT NICPOWEROFF","340"},
    {"EVENT DHCPSVRERR","341"},
    {"EVENT DHCPCAQUIRE","342"},
    {"EVENT DHCPCRELEASE","343"},
    {"EVENT DHCPCDEPENDPBR","344"},
    {"EVENT ROUTE6DOWN","345"},
    {"EVENT ROUTE6UP","346"},
    {"EVENT UNKNOWN","347"},
    {"CLI CMD_EXECUTED","399"},
    {"API CMD_EXECUTED","400"},
    {"APPFW APPFW_STARTURL","401"},
    {"APPFW_STARTURL","401"},
    {"APPFW APPFW_DENYURL","402"},
    {"APPFW APPFW_CONTENT_TYPE","403"},
    {"APPFW APPFW_REFERER_HEADER","404"},
    {"APPFW APPFW_CSRF_TAG","405"},
    {"APPFW APPFW_XSS","406"},
    {"APPFW_XSS","406"},
    {"APPFW APPFW_XML_XSS","407"},
    {"APPFW APPFW_SQL","408"},
    {"APPFW APPFW_XML_SQL","409"},
    {"APPFW APPFW_COOKIE","410"},
    {"APPFW APPFW_FIELDCONSISTENCY","411"},
    {"APPFW APPFW_BUFFEROVERFLOW_URL","412"},
    {"APPFW APPFW_BUFFEROVERFLOW_COOKIE","413"},
    {"APPFW APPFW_BUFFEROVERFLOW_HDR","414"},
    {"APPFW APPFW_FIELDFORMAT","415"},
    {"APPFW APPFW_SAFECOMMERCE","416"},
    {"APPFW APPFW_SAFECOMMERCE_XFORM","417"},
    {"APPFW APPFW_SAFEOBJECT","418"},
    {"APPFW APPFW_POLICY_HIT","419"},
    {"APPFW APPFW_POLICY_HIT_BUILTIN","420"},
    {"APPFW APPFW_MAX_UPLOADS","421"},
    {"APPFW APPFW_SIGNATURE_MATCH","422"},
    {"APPFW_SIGNATURE_MATCH","422"},
    {"APPFW AF_BIND_TO_PROFILE","423"},
    {"APPFW AF_BIND_XML_TO_PROFILE","424"},
    {"APPFW AF_ADD_FIELDTYPE","425"},
    {"APPFW AF_ADD_PROFILE","426"},
    {"APPFW AF_RM_FIELDTYPE","427"},
    {"APPFW AF_RM_PROFILE","428"},
    {"APPFW AF_ADD_CFFIELD","429"},
    {"APPFW AF_RM_CFFIELD","430"},
    {"APPFW AF_400_RESP","431"},
    {"APPFW AF_MEMORY_ERR","432"},
    {"APPFW AF_MALFORMED_REQ_ERR","433"},
    {"APPFW AF_UTHREAD_STACK_ERR","434"},
    {"APPFW AF_SIGNATURE_ERR","435"},
    {"APPFW APPFW_XML_ATTACHMENT_FOUND","436"},
    {"APPFW APPFW_XML_ATTACHMENT_ERR_CALLBACK_NULL","437"},
    {"APPFW APPFW_XML_ATTACHMENT_ERR_INVALIDHEADER","438"},
    {"APPFW APPFW_XML_ATTACHMENT_ERR_INVALID_HEADER","439"},
    {"APPFW APPFW_XML_ATTACHMENT_ERR_BOUNDARY_MISMATCH","440"},
    {"APPFW APPFW_XML_ERR_NO_ATTACHMENT_BOUNDARY","441"},
    {"APPFW APPFW_XML_ATTACHMENT_ERR_MAX_SIZE","442"},
    {"APPFW APPFW_XML_ATTACHMENT_ERR_CONTENT_TYPE","443"},
    {"APPFW APPFW_XML_DDOS_ERR_MSG_SEND_FAIL","444"},
    {"APPFW APPFW_XML_DOS_ERR_CHAR_DATA_LENGTH","445"},
    {"APPFW APPFW_XML_DOS_ERR_DTD","446"},
    {"APPFW APPFW_XML_DOS_ERR_EXT_ENTITY","447"},
    {"APPFW APPFW_XML_DOS_ERR_MAX","448"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_ATTRIBUTES","449"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_ATTRIBUTE_NAME_LENGTH","450"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_ATTRIBUTE_VALUE_LENGTH","451"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_ELEMENTS","452"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_ELEMENT_CHILDREN","453"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_ELEMENT_DEPTH","454"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_ELEMENT_NAME_LENGTH","455"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_FILE_SIZE","456"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_NODES","457"},
    {"APPFW APPFW_XML_DOS_ERR_MIN_FILE_SIZE","458"},
    {"APPFW APPFW_XML_ERR_NOT_WELLFORMED","459"},
    {"APPFW APPFW_XML_DOS_ERR_PI","460"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_NAMESPACES","461"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_NAMESPACEURI_LENGTH","462"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_ENTITY_EXPANSION_DEPTH","463"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_ENTITY_EXPANSIONS","464"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_SOAPARRAY_SIZE","465"},
    {"APPFW APPFW_XML_DOS_ERR_MAX_SOAPARRAY_RANK","466"},
    {"APPFW APPFW_XML_ERR_CUSTOM","467"},
    {"APPFW APPFW_XML_ERR_DDOS_CONNECT_TO_SERVER_FAILED","468"},
    {"APPFW APPFW_XML_ERR_DDOS_INTERATION_SOCKET_OPEN_FAIL","469"},
    {"APPFW APPFW_XML_ERR_DDOS_INVALID_CONFIG_FILE","470"},
    {"APPFW APPFW_XML_ERR_DDOS_NO_FOLDER_INSTALLATION_PATH","471"},
    {"APPFW APPFW_XML_ERR_DDOS_OPEN_CONFIG_FILE_FAIL","472"},
    {"APPFW APPFW_XML_ERR_DOS_TRIGGERED","473"},
    {"APPFW APPFW_XML_ERR_ENV_NOT_SET","474"},
    {"APPFW APPFW_XML_ERR_HASH_INSERT","475"},
    {"APPFW APPFW_XML_ERR_HASH_LOOKUP","476"},
    {"APPFW APPFW_XML_ERR_INITIALIZING_TOKENIZER","477"},
    {"APPFW APPFW_XML_ERR_INVALID_FILE","478"},
    {"APPFW APPFW_XML_ERR_INVALID_STATE","479"},
    {"APPFW APPFW_XML_ERR_INVALID_XPATH","480"},
    {"APPFW APPFW_XML_ERR_LOW_MEMORY","481"},
    {"APPFW APPFW_XML_ERR_CHARDATA_LIMIT_EXCEEDED","482"},
    {"APPFW APPFW_XML_ERR_MALFORMED_ADDRESS","483"},
    {"APPFW APPFW_XML_ERR_NO_DIME","484"},
    {"APPFW APPFW_XML_ERR_OPERATION_CALLBACK","485"},
    {"APPFW APPFW_XML_ERR_PREFIX_LENGTH_EXCEEDED","486"},
    {"APPFW APPFW_XML_ERR_READ_FAILED","487"},
    {"APPFW APPFW_XML_ERR_STREAM_POP","488"},
    {"APPFW APPFW_XML_ERR_STREAM_PUSH","489"},
    {"APPFW APPFW_XML_ERR_UNSUPPORTED_PORT","490"},
    {"APPFW APPFW_XML_ERR_UNSUPPORTED_PROTOCOL","491"},
    {"APPFW APPFW_XML_ERR_VALIDATION_FAILED","492"},
    {"APPFW APPFW_XML_PACKET_PROCESSING_ERR_CONTEXT_NULL","493"},
    {"APPFW APPFW_XML_PACKET_PROCESSING_ERR_CONTEXT_STATE_NULL","494"},
    {"APPFW APPFW_XML_PACKET_PROCESSING_ERR_MESSAGE_CONFIG_NULL","495"},
    {"APPFW APPFW_XML_VALIDATION_ERR_ABSTRACT_ELEMENT","496"},
    {"APPFW APPFW_XML_VALIDATION_ERR_ABSTRACT_TYPE","497"},
    {"APPFW APPFW_XML_VALIDATION_ERR_ADDHEADERS","498"},
    {"APPFW APPFW_XML_VALIDATION_ERR_ATTRIBUTE_MAX_OCCURS","499"},
    {"APPFW APPFW_XML_VALIDATION_ERR_ATTRIBUTE_MIN_OCCURS","500"},
    {"APPFW APPFW_XML_VALIDATION_ERR_COMPILED_WSDL","501"},
    {"APPFW APPFW_XML_VALIDATION_ERR_CONTENT_MODEL_VIOLATED","502"},
    {"APPFW APPFW_XML_VALIDATION_ERR_CORRUPT_COMPILED_WSDL","503"},
    {"APPFW APPFW_XML_VALIDATION_ERR_CORRUPT_SCHEMA","504"},
    {"APPFW APPFW_XML_VALIDATION_ERR_DATATYPE_ENGINE_INIT","505"},
    {"APPFW APPFW_XML_VALIDATION_ERR_INTERNAL","506"},
    {"APPFW APPFW_XML_VALIDATION_ERR_INVALID_ATTRIBUTE","507"},
    {"APPFW APPFW_XML_VALIDATION_ERR_INVALID_COMBINATION","508"},
    {"APPFW APPFW_XML_VALIDATION_ERR_INVALID_COMPILED_WSDL","509"},
    {"APPFW APPFW_XML_VALIDATION_ERR_INVALID_CONTENT_MODEL","510"},
    {"APPFW APPFW_XML_VALIDATION_ERR_INVALID_DATATYPE","511"},
    {"APPFW APPFW_XML_VALIDATION_ERR_INVALID_ELEMENT","512"},
    {"APPFW APPFW_XML_VALIDATION_ERR_INVALID_FILE","513"},
    {"APPFW APPFW_XML_VALIDATION_ERR_INVALID_TYPE_SUBSTITUTION","514"},
    {"APPFW APPFW_XML_VALIDATION_ERR_LOADING","515"},
    {"APPFW APPFW_XML_VALIDATION_ERR_MAX","516"},
    {"APPFW APPFW_XML_VALIDATION_ERR_NOSERVICEURL","517"},
    {"APPFW APPFW_XML_VALIDATION_ERR_NOT_SUPPORTED","518"},
    {"APPFW APPFW_XML_VALIDATION_ERR_SOAP_BODY","519"},
    {"APPFW APPFW_XML_VALIDATION_ERR_SOAP_ENVELOPE","520"},
    {"APPFW APPFW_XML_VALIDATION_ERR_SOAP_HEADER","521"},
    {"APPFW APPFW_XML_VALIDATION_ERR_UNBOUNDED_PREFIX","522"},
    {"APPFW APPFW_XML_VALIDATION_LOAD_ERR_CONTENTS_CANNOT_BE_NIL","523"},
    {"APPFW APPFW_XML_VALIDATION_LOAD_ERR_NIL_WITH_CONTENTS","524"},
    {"APPFW APPFW_XML_VALIDATION_ERR_REX_STACK_OVERFLOW","525"},
    {"APPFW APPFW_XML_VALIDATION_ERR_REX_STACK_EMPTY","526"},
    {"APPFW APPFW_XML_VALIDATION_ERR_SOAPBODY_EMPTY","527"},
    {"APPFW APPFW_XML_GENERIC_ERR_EMPTYBODY_REQ","528"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_ELEMENT_INVALID_DATATYPE_VALUE","529"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_ELEMENT_INVALID_LOCATION","530"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_FACET_MISMATCH","531"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_FAILED","532"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_INVALID_ATTRIBUTE_VALUE","533"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_INVALID_DATATYPE","534"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_INVALID_SCHEMA_NODE_TYPE","535"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_INVALID_VALUE_FOR_FIXED","536"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_LIST_LENGTH_GT_MAX","537"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_LIST_LENGTH_INVALID","538"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_LIST_LENGTH_LT_MIN","539"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_MAX","540"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_REQUIRED_ATTRIBUTE","541"},
    {"APPFW APPFW_XML_VALIDATOR_LOAD_ERR_SCHEMA_COMPILATION","542"},
    {"APPFW APPFW_XML_VALIDA TOR_LOAD_ERR_WSDL_COMPILATION","543"},
    {"APPFW APPFW_XML_WSI_ERR_ACCELEMENTNAMESPACED","544"},
    {"APPFW APPFW_XML_WSI_ERR_ARRAYTYPE","545"},
    {"APPFW APPFW_XML_WSI_ERR_BAD_ENV_NAMESPACE","546"},
    {"APPFW APPFW_XML_WSI_ERR_BINDINGFAULTRESP","547"},
    {"APPFW APPFW_XML_WSI_ERR_BODY_CHILD_NAMESPACE","548"},
    {"APPFW APPFW_XML_WSI_ERR_BODY_ENV_NAMESPACE","549"},
    {"APPFW APPFW_XML_WSI_ERR_CHILDAFTERBODY","550"},
    {"APPFW APPFW_XML_WSI_ERR_CLAIM_MUSTUNDERSTAND","551"},
    {"APPFW APPFW_XML_WSI_ERR_CTXT_NULL","552"},
    {"APPFW APPFW_XML_WSI_ERR_DOCTYPEALLOWED","553"},
    {"APPFW APPFW_XML_WSI_ERR_DOT_NOTATION","554"},
    {"APPFW APPFW_XML_WSI_ERR_ENCODINGSTYLE","555"},
    {"APPFW APPFW_XML_WSI_ERR_ENCODINGSTYLECHILD","556"},
    {"APPFW APPFW_XML_WSI_ERR_ENCODINGSTYLEGRANDCHILD","557"},
    {"APPFW APPFW_XML_WSI_ERR_ENVELEMENTSNOATTRIBUTES","558"},
    {"APPFW APPFW_XML_WSI_ERR_ENVNONAMESPACE","559"},
    {"APPFW APPFW_XML_WSI_ERR_GOODRESPONSE200","560"},
    {"APPFW APPFW_XML_WSI_ERR_HEADER_HAS_WSICLAIM","561"},
    {"APPFW APPFW_XML_WSI_ERR_HTTP","562"},
    {"APPFW APPFW_XML_WSI_ERR_ISHTTPPOST","563"},
    {"APPFW APPFW_XML_WSI_ERR_ISUTF8OR16","564"},
    {"APPFW APPFW_XML_WSI_ERR_MSGHASALLHEADERS","565"},
    {"APPFW APPFW_XML_WSI_ERR_MUSTUNDERSTAND","566"},
    {"APPFW APPFW_XML_WSI_ERR_NODEPLOYED","567"},
    {"APPFW APPFW_XML_WSI_ERR_NOENVELOPEWSDLMATCH","568"},
    {"APPFW APPFW_XML_WSI_ERR_NONPOSTREQUEST","569"},
    {"APPFW APPFW_XML_WSI_ERR_NONXMLREQUEST","570"},
    {"APPFW APPFW_XML_WSI_ERR_NOPORTURL","571"},
    {"APPFW APPFW_XML_WSI_ERR_NOREQWSDLMATCH","572"},
    {"APPFW APPFW_XML_WSI_ERR_NORESPWSDLMATCH","573"},
    {"APPFW APPFW_XML_WSI_ERR_NOWSDLDEPLOYED","574"},
    {"APPFW APPFW_XML_WSI_ERR_ONEWAYRESPONSE","575"},
    {"APPFW APPFW_XML_WSI_ERR_RESPONSESTATUS200OR202","576"},
    {"APPFW APPFW_XML_WSI_ERR_RESPONSEWRAPPED","577"},
    {"APPFW APPFW_XML_WSI_ERR_SOAPACTIONHEADERMATCH","578"},
    {"APPFW APPFW_XML_WSI_ERR_SOAPACTIONQUOTED","579"},
    {"APPFW APPFW_XML_WSI_ERR_SOAPFAULTALLOWEDCHILD","580"},
    {"APPFW APPFW_XML_WSI_ERR_SOAPFAULTCHILDQ","581"},
    {"APPFW APPFW_XML_WSI_ERR_SOAPFAULTINHTTP","582"},
    {"APPFW APPFW_XML_WSI_ERR_SOAPFAULTNONENV","583"},
    {"APPFW APPFW_XML_WSI_ERR_SOAPGOODXML10","584"},
    {"APPFW APPFW_XML_WSI_ERR_STDFAULTCODE","585"},
    {"APPFW APPFW_XML_WSI_ERR_USEHTTP10OR11","586"},
    {"APPFW APPFW_XML_WSI_ERR_USEHTTP11","587"},
    {"APPFW APPFW_XML_WSI_ERR_WSICLAIMSWELLFORMED","588"},
    {"APPFW APPFW_XML_WSI_ERR_WSI_LIST_NULL","589"},
    {"APPFW APPFW_XML_WSI_ERR_XMLPI","590"},
    {"APPFW APPFW_XML_WSI_ERR_XSINIL","591"},
    {"APPFW APPFW_XML_XSD_COMPILE_INIT_ERR","592"},
    {"APPFW APPFW_XML_XSD_COMPILE_LOADXSD_ERR","593"},
    {"APPFW APPFW_XML_XSD_COMPILE_NOMODEL_ERR","594"},
    {"APPFW APPFW_XML_XSD_COMPILE_PARSE_ERR","595"},
    {"APPFW APPFW_XML_XSD_COMPILE_UNEXPECTED_ERR","596"},
    {"APPFW APPFW_XML_ERR_SOAP_FAULT","597"},
    {"APPFW APPFW_XML_SOAP_FAULT_CONTENTS","598"},
    {"APPFW AF_INVALID_HTTP_HEADER","599"},
    {"APPFW APPFW_CCARD_MATCH_IN_SIGNATURES","600"},
    {"APPFW_RESP APPFW_XML_XSS","601"},
    {"APPFW_RESP APPFW_XML_SQL","602"},
    {"APPFW_RESP APPFW_XML_ATTACHMENT_FOUND","603"},
    {"APPFW_RESP APPFW_XML_ATTACHMENT_ERR_CALLBACK_NULL","604"},
    {"APPFW_RESP APPFW_XML_ATTACHMENT_ERR_INVALIDHEADER","605"},
    {"APPFW_RESP APPFW_XML_ATTACHMENT_ERR_INVALID_HEADER","606"},
    {"APPFW_RESP APPFW_XML_ATTACHMENT_ERR_BOUNDARY_MISMATCH","607"},
    {"APPFW_RESP APPFW_XML_ERR_NO_ATTACHMENT_BOUNDARY","608"},
    {"APPFW_RESP APPFW_XML_ATTACHMENT_ERR_MAX_SIZE","609"},
    {"APPFW_RESP APPFW_XML_ATTACHMENT_ERR_CONTENT_TYPE","610"},
    {"APPFW_RESP APPFW_XML_DDOS_ERR_MSG_SEND_FAIL","611"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_CHAR_DATA_LENGTH","612"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_DTD","613"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_EXT_ENTITY","614"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX","615"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_ATTRIBUTES","616"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_ATTRIBUTE_NAME_LENGTH","617"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_ATTRIBUTE_VALUE_LENGTH","618"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_ELEMENTS","619"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_ELEMENT_CHILDREN","620"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_ELEMENT_DEPTH","621"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_ELEMENT_NAME_LENGTH","622"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_FILE_SIZE","623"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_NODES","624"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MIN_FILE_SIZE","625"},
    {"APPFW_RESP APPFW_XML_ERR_NOT_WELLFORMED","626"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_PI","627"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_NAMESPACES","628"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_NAMESPACEURI_LENGTH","629"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_ENTITY_EXPANSION_DEPTH","630"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_ENTITY_EXPANSIONS","631"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_SOAPARRAY_SIZE","632"},
    {"APPFW_RESP APPFW_XML_DOS_ERR_MAX_SOAPARRAY_RANK","633"},
    {"APPFW_RESP APPFW_XML_ERR_CUSTOM","634"},
    {"APPFW_RESP APPFW_XML_ERR_DDOS_CONNECT_TO_SERVER_FAILED","635"},
    {"APPFW_RESP APPFW_XML_ERR_DDOS_INTERATION_SOCKET_OPEN_FAIL","636"},
    {"APPFW_RESP APPFW_XML_ERR_DDOS_INVALID_CONFIG_FILE","637"},
    {"APPFW_RESP APPFW_XML_ERR_DDOS_NO_FOLDER_INSTALLATION_PATH","638"},
    {"APPFW_RESP APPFW_XML_ERR_DDOS_OPEN_CONFIG_FILE_FAIL","639"},
    {"APPFW_RESP APPFW_XML_ERR_DOS_TRIGGERED","640"},
    {"APPFW_RESP APPFW_XML_ERR_ENV_NOT_SET","641"},
    {"APPFW_RESP APPFW_XML_ERR_HASH_INSERT","642"},
    {"APPFW_RESP APPFW_XML_ERR_HASH_LOOKUP","643"},
    {"APPFW_RESP APPFW_XML_ERR_INITIALIZING_TOKENIZER","644"},
    {"APPFW_RESP APPFW_XML_ERR_INVALID_FILE","645"},
    {"APPFW_RESP APPFW_XML_ERR_INVALID_STATE","646"},
    {"APPFW_RESP APPFW_XML_ERR_INVALID_XPATH","647"},
    {"APPFW_RESP APPFW_XML_ERR_LOW_MEMORY","648"},
    {"APPFW_RESP APPFW_XML_ERR_CHARDATA_LIMIT_EXCEEDED","649"},
    {"APPFW_RESP APPFW_XML_ERR_MALFORMED_ADDS","650"},
    {"APPFW_RESP APPFW_XML_ERR_NO_DIME","651"},
    {"APPFW_RESP APPFW_XML_ERR_OPERATION_CALLBACK","652"},
    {"APPFW_RESP APPFW_XML_ERR_PREFIX_LENGTH_EXCEEDED","653"},
    {"APPFW_RESP APPFW_XML_ERR_READ_FAILED","654"},
    {"APPFW_RESP APPFW_XML_ERR_STREAM_POP","655"},
    {"APPFW_RESP APPFW_XML_ERR_STREAM_PUSH","656"},
    {"APPFW_RESP APPFW_XML_ERR_UNSUPPORTED_PORT","657"},
    {"APPFW_RESP APPFW_XML_ERR_UNSUPPORTED_PROTOCOL","658"},
    {"APPFW_RESP APPFW_XML_ERR_VALIDATION_FAILED","659"},
    {"APPFW_RESP APPFW_XML_PACKET_PROCESSING_ERR_CONTEXT_NULL","660"},
    {"APPFW_RESP APPFW_XML_PACKET_PROCESSING_ERR_CONTEXT_STATE_NULL","661"},
    {"APPFW_RESP APPFW_XML_PACKET_PROCESSING_ERR_MESSAGE_CONFIG_NULL","662"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_ABSTRACT_ELEMENT","663"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_ABSTRACT_TYPE","664"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_ADDHEADERS","665"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_ATTRIBUTE_MAX_OCCURS","666"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_ATTRIBUTE_MIN_OCCURS","667"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_COMPILED_WSDL","668"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_CONTENT_MODEL_VIOLATED","669"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_CORRUPT_COMPILED_WSDL","670"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_CORRUPT_SCHEMA","671"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_DATATYPE_ENGINE_INIT","672"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_INTERNAL","673"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_INVALID_ATTRIBUTE","674"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_INVALID_COMBINATION","675"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_INVALID_COMPILED_WSDL","676"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_INVALID_CONTENT_MODEL","677"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_INVALID_DATATYPE","678"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_INVALID_ELEMENT","679"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_INVALID_FILE","680"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_INVALID_TYPE_SUBSTITUTION","681"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_LOADING","682"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_MAX","683"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_NOSERVICEURL","684"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_NOT_SUPPORTED","685"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_SOAP_BODY","686"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_SOAP_ENVELOPE","687"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_SOAP_HEADER","688"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_UNBOUNDED_PREFIX","689"},
    {"APPFW_RESP APPFW_XML_VALIDATION_LOAD_ERR_CONTENTS_CANNOT_BE_NIL","690"},
    {"APPFW_RESP APPFW_XML_VALIDATION_LOAD_ERR_NIL_WITH_CONTENTS","691"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_REX_STACK_OVERFLOW","692"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_REX_STACK_EMPTY","693"},
    {"APPFW_RESP APPFW_XML_VALIDATION_ERR_SOAPBODY_EMPTY","694"},
    {"APPFW_RESP APPFW_XML_GENERIC_ERR_EMPTYBODY_REQ","695"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_ELEMENT_INVALID_DATATYPE_VALUE","696"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_ELEMENT_INVALID_LOCATION","697"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_FACET_MISMATCH","698"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_FAILED","699"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_INVALID_ATTRIBUTE_VALUE","700"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_INVALID_DATATYPE","701"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_INVALID_SCHEMA_NODE_TYPE","702"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_INVALID_VALUE_FOR_FIXED","703"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_LIST_LENGTH_GT_MAX","704"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_LIST_LENGTH_INVALID","705"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_LIST_LENGTH_LT_MIN","706"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_MAX","707"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_REQUIRED_ATTRIBUTE","708"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_SCHEMA_COMPILATION","709"},
    {"APPFW_RESP APPFW_XML_VALIDATOR_LOAD_ERR_WSDL_COMPILATION","710"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_ACCELEMENTNAMESPACED","711"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_ARRAYTYPE","712"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_BAD_ENV_NAMESPACE","713"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_BINDINGFAULTIRESP","714"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_BODY_CHILD_NAMESPACE","715"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_BODY_ENV_NAMESPACE","716"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_CHILDAFTERBODY","717"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_CLAIM_MUSTUNDERSTAND","718"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_CTXT_NULL","719"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_DOCTYPEALLOWED","720"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_DOT_NOTATION","721"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_ENCODINGSTYLE","722"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_ENCODINGSTYLECHILD","723"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_ENCODINGSTYLEGRANDCHILD","724"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_ENVELEMENTSNOATTRIBUTES","725"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_ENVNONAMESPACE","726"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_GOODRESPONSE200","727"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_HEADER_HAS_WSICLAIM","728"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_HTTP","729"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_ISHTTPPOST","730"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_ISUTF8OR16","731"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_MSGHASALLHEADERS","732"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_MUSTUNDERSTAND","733"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_NODEPLOYED","734"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_NOENVELOPEWSDLMATCH","735"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_NONPOSTREQUEST","736"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_NONXMLREQUEST","737"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_NOPORTURL","738"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_NOREQWSDLMATCH","739"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_NORESPWSDLMATCH","740"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_NOWSDLDEPLOYED","741"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_ONEWAYRESPONSE","742"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_RESPONSESTATUS200OR202","743"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_RESPONSEWRAPPED","744"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_SOAPACTIONHEADERMATCH","745"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_SOAPACTIONQUOT ED","746"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_SOAPFAULTALLOWEDCHILD","747"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_SOAPFAULTCHILDQ","748"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_SOAPFAULTINHTTP","749"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_SOAPFAULTNONENV","750"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_SOAPGOODXML10","751"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_STDFAULTCODE","752"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_USEHTTP10OR11","753"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_USEHTTP11","754"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_WSICLAIMSWELLFORMED","755"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_WSI_LIST_NULL","756"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_XMLPI","757"},
    {"APPFW_RESP APPFW_XML_WSI_ERR_XSINIL","758"},
    {"APPFW_RESP APPFW_XML_XSD_COMPILE_INIT_ERR","759"},
    {"APPFW_RESP APPFW_XML_XSD_COMPILE_LOADXSD_ERR","760"},
    {"APPFW_RESP APPFW_XML_XSD_COMPILE_NOMODEL_ERR","761"},
    {"APPFW_RESP APPFW_XML_XSD_COMPILE_PARSE_ERR","762"},
    {"APPFW_RESP APPFW_XML_XSD_COMPILE_UNEXPECTED_ERR","763"},
    {"APPFW_RESP APPFW_XML_ERR_SOAP_FAULT","764"},
    {"APPFW_RESP APPFW_XML_SOAP_FAULT_CONTENTS","765"},
    {"APPFW_RESP AF_INVALID_HTTP_HEADER","766"},
    {"APPFW_RESP APPFW_CCARD_MATCH_IN_SIGNATURES","767"},
    {"ROUTING Message","768"},
    {"EVENT NICLOW_THROUGHPUT","1021"},
    {"EVENT NICNORMAL_THROUGHPUT","1023"},
    {"", ""}
};

static int match_with_pcre_jit(pcre *compiled, pcre_extra *extra, pcre_jit_stack *jit_stack,
                               int ovector[CF_MAX_PCRE_SUB_STR_NUM], const char *buf) {
    int pcreErrorOffset;
    int pcreExecRet = 0;
    int ret = 0;

    pcre_assign_jit_stack(extra, NULL, jit_stack);

    pcreExecRet = pcre_jit_exec(compiled,
                                extra,
                                buf,
                                strlen(buf),        // length of string
                                0,                      // Start looking at this point
                                0,                      // OPTIONS
                                ovector,
                                CF_MAX_PCRE_SUB_STR_NUM,
                                jit_stack);


    if (pcreExecRet < 0) { // Something bad happened..
        switch (pcreExecRet) {
            case PCRE_ERROR_NOMATCH      :
                break;
            case PCRE_ERROR_NULL         :
            case PCRE_ERROR_BADOPTION    :
            case PCRE_ERROR_BADMAGIC     :
            case PCRE_ERROR_UNKNOWN_NODE :
            case PCRE_ERROR_NOMEMORY     :
                break;
            default:
                break;
        }
    } else {

        if (pcreExecRet == 0) {
            pcreExecRet = CF_MAX_PCRE_SUB_STR_NUM / 3;
        }
        ret = pcreExecRet;
    }

    return ret;
}

int normalize_date_fortigate(pcre *compiled, pcre_extra *extra, pcre_jit_stack *jit_stack, const char * date, char *ret_str)
{
    //Fortigate date=2015-03-17 time=22:03:55
    const char *psubStrMatchStr;
    int ovector[CF_MAX_PCRE_SUB_STR_NUM];
    int ret = match_with_pcre_jit(compiled, extra, jit_stack, ovector, date);
    if(ret > 0){
        if(pcre_get_named_substring(compiled, date, ovector, ret, "year", &(psubStrMatchStr)) >= 0){
            strcpy(ret_str, psubStrMatchStr);
            strcat(ret_str, "-");
        }
        pcre_free_substring(psubStrMatchStr);

        if(pcre_get_named_substring(compiled, date, ovector, ret, "month", &(psubStrMatchStr)) >= 0){
            strcat(ret_str, psubStrMatchStr);
            strcat(ret_str, "-");
        }
        pcre_free_substring(psubStrMatchStr);

        if(pcre_get_named_substring(compiled, date, ovector, ret, "day", &(psubStrMatchStr)) >= 0){
            strcat(ret_str, psubStrMatchStr);
            strcat(ret_str, " ");
        }
        pcre_free_substring(psubStrMatchStr);

        if(pcre_get_named_substring(compiled, date, ovector, ret, "hour", &(psubStrMatchStr)) >= 0){
            strcat(ret_str, psubStrMatchStr);
            strcat(ret_str, ":");
        }
        pcre_free_substring(psubStrMatchStr);

        if(pcre_get_named_substring(compiled, date, ovector, ret, "minute", &(psubStrMatchStr)) >= 0){
            strcat(ret_str, psubStrMatchStr);
            strcat(ret_str, ":");
        }
        pcre_free_substring(psubStrMatchStr);

        if(pcre_get_named_substring(compiled, date, ovector, ret, "second", &(psubStrMatchStr)) >= 0){
            strcat(ret_str, psubStrMatchStr);
        }
        pcre_free_substring(psubStrMatchStr);
    }
    else{//no match
        strcat(ret_str,date);
    }
    return strlen(ret_str) + 1;
}

int fortigate_sid(pcre *compiled, pcre_extra *extra, pcre_jit_stack *jit_stack, const char * attack_id, char *ret_str)
{
    /*def fortigate_sid( self, attackId=""):

    if len(attackId) <8 :
    attackId = int(str(10) + str(attackId))

    return attackId
    */
    
    if(strlen(attack_id) < 8){
        strcpy(ret_str,"10");
    }

    strcat(ret_str,attack_id);
    
    return strlen(ret_str)+1;
}

int normalize_protocol(pcre *compiled, pcre_extra *extra, pcre_jit_stack *jit_stack, const char * protocol, char *ret_str)
{
    if(strcmp(protocol, "1"))
        strcpy(ret_str, "icmp");
    else if(strcmp(protocol, "6"))
        strcpy(ret_str, "tcp");
    else if(strcmp(protocol, "17"))
        strcpy(ret_str, "udp");
    else
        strcpy(ret_str, protocol);
        
    return strlen(ret_str) + 1;
}

int normalize_date_citrix(pcre *compiled, pcre_extra *extra, pcre_jit_stack *jit_stack, const char * date, char *ret_str)
{
    // citrix 02/28/2013:12:00:00
    const char *psubStrMatchStr;
    int ovector[CF_MAX_PCRE_SUB_STR_NUM];
    int ret = match_with_pcre_jit(compiled, extra, jit_stack, ovector, date);
    if(ret > 0){
        if(pcre_get_named_substring(compiled, date, ovector, ret, "year", &(psubStrMatchStr)) >= 0){
            strcpy(ret_str, psubStrMatchStr);
            strcat(ret_str, "-");
        }
        pcre_free_substring(psubStrMatchStr);

        if(pcre_get_named_substring(compiled, date, ovector, ret, "month", &(psubStrMatchStr)) >= 0){
            strcat(ret_str, psubStrMatchStr);
            strcat(ret_str, "-");
        }
        pcre_free_substring(psubStrMatchStr);

        if(pcre_get_named_substring(compiled, date, ovector, ret, "day", &(psubStrMatchStr)) >= 0){
            strcat(ret_str, psubStrMatchStr);
            strcat(ret_str, " ");
        }
        pcre_free_substring(psubStrMatchStr);

        if(pcre_get_named_substring(compiled, date, ovector, ret, "hour", &(psubStrMatchStr)) >= 0){
            strcat(ret_str, psubStrMatchStr);
            strcat(ret_str, ":");
        }
        pcre_free_substring(psubStrMatchStr);

        if(pcre_get_named_substring(compiled, date, ovector, ret, "minute", &(psubStrMatchStr)) >= 0){
            strcat(ret_str, psubStrMatchStr);
            strcat(ret_str, ":");
        }
        pcre_free_substring(psubStrMatchStr);

        if(pcre_get_named_substring(compiled, date, ovector, ret, "second", &(psubStrMatchStr)) >= 0){
            strcat(ret_str, psubStrMatchStr);
        }
        pcre_free_substring(psubStrMatchStr);
    }
    else{
        strcat(ret_str,date);
    }
    return strlen(ret_str) + 1;
}

int translate_citrix(pcre *compiled, pcre_extra *extra, pcre_jit_stack *jit_stack, const char * key, char *ret_str)
{
    int key_found = 0;
    int dindex = 0;
    for (dindex = 0; strcmp(c_dict[dindex].key, ""); dindex++) {
        if(!strcmp(c_dict[dindex].key, key)){
            strcpy(ret_str, c_dict[dindex].value);
            key_found = 1;
            break;
        }
    }

    if(!key_found)
        strcat(ret_str, key);
    
    return strlen(ret_str)+1;
}